### ISSUE TITLE
[Feature Request] Oscillation Mode when Activating

### ISSUE THREAD

**Issue by dVIAN13** [lukasroegner/homebridge-dyson-pure-cool#124]
Hello, first off I'd like to say thank you! This plugin is done so well. I'd like to know if a feature could be added to automatically enable Oscillation when the device is activated via HomeKit. Obviously, this would be an additional option just as 'Enable Auto Mode'. Thank you, again!

**Comment by lukasroegner** [comment]
Hi @dVIAN13,

I wonder whether you could just add a new automation to HomeKit: "if value of Active Characteristic changes to ON, set Oscillation ON"?. 
If that's not possible, I can implement a setting for that.

**Comment by dVIAN13** [comment]
@lukasroegner, thanks for the reply and suggestion. I just tried it, and unfortunately, it did not work as expected. It turned the Oscillate on, however also turned auto mode off. I had to do it with a 'scene' because it appears from within the iOS home app, you cannot set a characteristic of a device you're detecting control of. Appreciate it!

**Comment by lukasroegner** [comment]
Implemented in latest version as a config option!

**Comment by dVIAN13** [comment]
Hello. Thank you for adding this! The latest version is not yet available via npm.

**Comment by lukasroegner** [comment]
Published now!

**Comment by joshjohanning** [comment]
Just came here to say, in case anyone else is looking for it, the fan itself won't oscillate if you 1) have a heater and 2) have the heat set to lower than what it is in the room.

Ie I had the HP-04 set to heat to 66 but it was already 68, so I was getting super confused as to why when I turned on the fan it wasn't oscillating even though I had `enableOscillationWhenActivating` enabled. 

This isn't anything with this plugin, it's just how the heater works (and actually kind of nice since it won't oscillate neutral air in the room when it's not heating). 

Hopefully this helps someone else not waste 15 minutes debugging :).
