### ISSUE TITLE
Temperature Setting Skips Values in Fahrenheit

### ISSUE THREAD

**Issue by Tyler-Seliber** [lukasroegner/homebridge-dyson-pure-cool#144]
When trying to adjust the temperature on my HP04 through HomeKit, I am unable to set precise temperatures. As you can see in the screen recording below, I can only set the temperature to be even between values of 64-72 °F, and in other ranges I can only set odd values. In some cases, you can see that even by moving the thermostat one notch the temperature value does not change, and sometimes it will jump to another position.

I enabled debug logging on Homebridge and saw that each time I set the temperature, the plugin logged 
`set TargetTemperature to <integer>: {"hmax":"<XXXX>"}`
and shows my set temperature in Celsius. I believe this may be related to issue #68 where the plugin only accepted integers for temperature settings, as my inputs seem to be properly converted to Celsius and then rounded to the nearest integer.

https://user-images.githubusercontent.com/42685071/103573298-032bd100-4e9c-11eb-8a84-94b62a434764.mov

**Comment by lzolner** [comment]
This has been happening to me for a few weeks now as well. Any help would be appreciated.

**Comment by lukasroegner** [comment]
Can you tell me the step size for Fahrenheit temperature in the Dyson app (min, max, step)?

**Comment by Tyler-Seliber** [comment]
The official Dyson Link app doesn't allow heating/temperature adjustments for safety regulations (see attached), but using the remote I was able to get the following values for heating:
  Min: 34 °F
  Max: 99 °F
  Step: 1 °F
This was done on a brand new HP04 Pure Hot + Cool
![IMG_80A5FE35F917-1](https://user-images.githubusercontent.com/42685071/105272220-e0b9d900-5b66-11eb-952f-ee05f60718db.jpeg)

**Comment by holmnathan** [comment]
Also experiencing the same Fahrenheit issue with an HP04 Pure Hot + Cool. It seems to be an issue with rounding from Celsius because the steps in Fahrenheit don't consistently increment by 2º.

`[12/23/2021, 12:42:44 AM] [homebridge-dyson-pure-cool] ZZ5-US-######## - set TargetTemperature to 21: {"hmax":"2940"}` *Snaps to 70ºF in Home app*
`[12/23/2021, 12:42:47 AM] [homebridge-dyson-pure-cool] ZZ5-US-######## - set TargetTemperature to 22: {"hmax":"2950"}` *Snaps to 72ºF in Home app*
`[12/23/2021, 12:42:49 AM] [homebridge-dyson-pure-cool] ZZ5-US-######## - set TargetTemperature to 23: {"hmax":"2960"}` *Snaps to 73ºF in Home app*
`[12/23/2021, 12:42:53 AM] [homebridge-dyson-pure-cool] ZZ5-US-######## - set TargetTemperature to 24: {"hmax":"2970"}` *Snaps to 75ºF in Home app*

**Comment by lukasroegner** [comment]
Fixed in 2.2.0 with the help of @mpiotrowski

**Comment by joshjohanning** [comment]
Also, I found that if you don't have your fan on (and perhaps heat function, I did), when it adds to HomeBridge and HomeKit, the current temperature shows up in Celsius. 

I had 2 of 3 fans w/ heat on, and those 2 added showing with current temperature as Fahrenheit. The 3rd fan was off, and it added as Celsius. I removed the fan, made sure it didn't appear in cache, turned it + heat on, and then re-added it.  Now it showed up as Fahrenheit.
