### ISSUE TITLE
API 401 sign in issue

### ISSUE THREAD

**Issue by themanontv** [lukasroegner/homebridge-dyson-pure-cool#180]
The plugin has stopped working overnight and doesn’t sign in anymore, it simply gives a 401 error

![93A7E0BF-A1FB-46FC-A129-D5D0435EAA0B](https://user-images.githubusercontent.com/39599137/114737678-2a1d5d00-9d3f-11eb-84f6-4594118da87e.jpeg)

**Comment by rfroom** [comment]
I am seeing same behavior.  Starting very recently.

**Comment by BaksiLi** [comment]
Have you tried to sign out and sign in on your iPhone? It will probably ask you to enter a 2FA code (from your email address).

**Comment by w00tslap** [comment]
@BaksiLi That worked for me. Thanks!

**Comment by rose-cottage** [comment]
Still no joy for me - Status Code: 400

**Comment by BaksiLi** [comment]
> Still no joy for me - Status Code: 400

I had this issue for a long time until I figured out how to solve it recently.

Here is what happened: It shows me the error 401 or 400, and if luckily it can be solved by the _sign out and sign in_ method, the error will come back in one or two days again.

I guess this is because homebridge is refreshing its link to the Dyson server too frequently and caused security concerns. The solution is therefore easy:- extend the `updateInterval` and `retrySignInInterval` in the config.

<img width="557" alt="Screenshot 2021-05-10 at 18 22 34" src="https://user-images.githubusercontent.com/26314680/117645032-b1ce7e00-b1bc-11eb-8702-bd308fb8f7cb.png">

You can find the config panel as above. Search for the line saying `"platform": "DysonPureCoolPlatform"` and add these two lines below:

```
            "platform": "DysonPureCoolPlatform",
            "updateInterval": 75000,
            "retrySignInInterval": 300000
``` 

Note that the config file is in JSON, so you need to add a comma to the end of a line if a consecutive line exists.

Click the SAVE button and **wait for a night or so**. Then **do the sign out and sign in trick** on your phone. Once you are ready, **restart** your Homebridge server and bobs your uncle!

I followed this method and have not had this problem again for a month. You should first use the same number as above and if it worked, slowly reduce the intervals until you find it comfortable.

Hope this helps.

**Comment by BaksiLi** [comment]
> sorry does not work for me :(

wait longer and do the sign out trick before restarting the server.

**Comment by henkied** [comment]
ehmm still same issue @BaksiLi 

[5/12/2021, 7:25:09 PM] [DysonPureCoolPlatform] Error while signing in. Status Code: 401
[5/12/2021, 7:25:09 PM] [DysonPureCoolPlatform] API could not be reached. Retry is disabled.

**Comment by lukasroegner** [comment]
See https://github.com/lukasroegner/homebridge-dyson-pure-cool/issues/166#issuecomment-841255154.
