### ISSUE TITLE
No Temp Setting Show for dyson air purifier formaldehyde

### ISSUE THREAD

**Issue by DannyType1** [lukasroegner/homebridge-dyson-pure-cool#198]
Hi

No temp setting shows up for the new Dyson air purifier formaldehyde that came out in March. Everything else works as it should do.

Thanks

Danny

**Comment by lukasroegner** [comment]
Can you provide the product name of the device? There are multiple "Formaldehyde" devices on the market:
- If it is an `HP07`, you can answer to #215 and close this issue
- If it is a `PH03`, you can answer to #219 and close this issue 
- If it is a `TP09`, you can answer to #225 and close this issue

If it is a different product, please install the latest version (2.3.5) of the plugin. On startup, you will be able to see a new log entry:

```
Device with serial number XXXXXXX: product type XXX
```

Report the product type to me, so that I can add it to the list of supported devices. Please also tell me which features are available (heating, humidifier, jet focus), so that the correct accessories and services are being exposed to HomeKit.
