### ISSUE TITLE
Auto-Oscillate Ignored If 'Night Mode' Toggle Used To Turn On Pure Hot + Cool

### ISSUE THREAD

**Issue by BananimusPrime** [lukasroegner/homebridge-dyson-pure-cool#207]
Hey, I've got `"enableOscillationWhenActivating"` set to true, and if I use the Homekit power button or if I slide the speed bar up to wherever I want it, the fan will turn on and automatically start oscillating. If, however, I turn the fan on by toggling Night mode to 'on', then it doesn't auto-oscillate, I have to turn the fan back off and use either the power toggle or the speed bar to turn it on again, then activate night mode, _then_ set it back to the speed that I wanted because night mode always overrides it to speed 4...

**Comment by lukasroegner** [comment]
This is by design. The options `enableOscillationWhenActivating` and `enableNightModeWhenActivating` are only considered when you use the on/off switch. Changing the behavior would be better in your specific case, other may have issues with their automations.

The `enableNightModeWhenActivating` setting has been added after you've create the issue, maybe the setting helps you with your use case.
