### ISSUE TITLE
Credentials wrong?

### ISSUE THREAD

**Issue by Christian-CFP** [lukasroegner/homebridge-dyson-pure-cool#93]
Hi Lucas,
I got the credentials from the the Dyson API (PH01) inside the log.
But it says wrong credentials for this serial no. if I set the credential in the config?

Copy and paste the exact same value....
If I do not set the credentials by hand it works just fine.

**Comment by lukasroegner** [comment]
Possible issues:
- You haven't set a room for the device in the Dyson app
- The room name contains a special character

**Comment by albliu** [comment]
This happened to me (I have TP02). After trying out a few things, I think it's because the name of my device contained a "TM" character, which made the JSON parsing function failed. I only have 1 device, so I manually changed the apiConfig.Name to remove the "TM" character, and now it seems like it works
